### PR TITLE
add assessment.md - identify issues and recommend fixes

### PR DESCRIPTION
**Pull request by mschwartz**
App is slow and generates white page when clicking on an employee.

I reviewed the app sources and used developer tools to figure out some issues and make recommendations here.  Rather than make a single Issue or multiple Issues, I submit this .md file instead.

### CODE REVIEW

**Comment by grgur** [comment]
Thanks for the assessment Mike. Can we use GitHub projects to list all these and work on them when ready?

**Comment by mschwartz** [comment]
Kent is working on this.

**Comment by Mrkezii** [comment]
@grgur we can use github projects so everyone can keep track of progress, thats fine by me.

**Comment by Mrkezii** [comment]
```
* Discover the cause of slow server at dir.modus.app.
   - Should be investigated, someone may want to look into this simultaneously. 
* Fix firefox bug
  - Have not been able to reproduce. 
  
* speed up loading of employee data list
  - I am confident that a huge chunk of time is spent actually doing some computation / normalisation of the modites data returned from slack, i suggest we have this as the next in priority after we fix the location issue. 
  
* fix the Location property bug
  - API response does not return the required field that the frontend is looking for, the reason why it was working for a few users was because we also returned stale (cached) data that used to work. ETA on this should be the next 24 hours, i think i am close to completion.

* Discover the 403 issue cause
  - I assume this is linked to the location issue, but will look into it soon.
  
* Discover the use of closure library (what's loading it)
  - I am assuming this is of a lower priority right now so will look into it once the major issues are fixed
```

**Comment by mschwartz** [comment]
Added to project board.

**Pull request closed without merging**
